# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Jack Kelly
email: jack@jack-kelly.com
description: "I try to mitigate climate change using computer science.  I am a Research Engineer at [DeepMind](https://deepmind.com), mostly working on energy problems. Previously, I worked on energy disaggregation as a post-doc at [Imperial College London](https://www.imperial.ac.uk)."
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://jack-kelly.com"
twitter_username: jack_kelly
github_username:  JackKelly
linkedin_username: jackkelly0

# Build settings
markdown: kramdown
theme: minima
incremental: true
gems:
  - jekyll-feed
  - jekyll-redirect-from
exclude:
  - Gemfile
  - Gemfile.lock
#  - "_posts/200*"
#  - "_posts/201[0-6]*"

timezone: Europe/London
minima:
  date_format: "%e %b %Y"

excerpt_separator: "<!--break-->"

google_analytics: UA-29040208-1

collections:
  posts:
    permalink: /blog/:name
  films:
    output: true
  taxonomy:
    output: true
    permalink: /taxonomy/term/:name
    
defaults:
  - scope:
      path: _films
      type: films
    values:
      layout: page-with-comments
      comments: true

header_pages:
  - publications.md
  - categories.html
  - films.html
  - about.md
  - search.html

disqus:
  shortname: jack-kelly
